### ISSUE TITLE
Does not compile on linux 4.13

### ISSUE THREAD

**Issue by obma** [astyonax/patched-RTS5227-5229#2] opened 2017-10-06 11:39 UTC
As commented here: https://aur.archlinux.org/packages/rts5227-dkms/?comments=all

> alter2000:
> ==> dkms install rts5227/1.07 -k 4.13.3-1-ARCH
> Error! Bad return status for module build on kernel: 4.13.3-1-ARCH (x86_64)
> Consult /var/lib/dkms/rts5227/1.07/build/make.log for more information.
> 
> And the log is here: https://hastebin.com/juqadumaxa.cs

**Comment by astyonax** [comment] 2017-10-09 13:16
Hi,  
I will have to take a more careful look at that, because it compiles well on my linux 4.13.4.

**Comment by ghost91-** [comment] 2017-11-03 16:42
I can confirm this. I am currently on 4.13.11 and I am getting the same error. It seems to be related to the new CONFIG_FORTIFY_SOURCE which is enabled by default since 4.13 (maybe it is disabled on your machine?).

**Comment by astyonax** [comment] 2017-11-29 15:17
I'm on ubuntu 16.04.3 LTS, and the kernel 4.13.4 is compiled with `CONFIG_FORTIFY_SOURCE=y`
(for information, the config is in `/boot/config-${version}`).. I didn't have time to dig more into the problem yet because I didn't have time to setup a more recent VM.

**Comment by astyonax** [comment] 2017-11-29 15:27
I know that this can be pedantic, but can you try with the same revision as mine (4.13.4) ?
Also can you share your config for the going-to-be-compiled kernel? So that I compare to mine

**Comment by Zibri** [comment] 2017-12-01 06:26
solved
https://github.com/Zibri/Realtek-rts5229-linux-driver

**Comment by astyonax** [comment] 2017-12-01 08:52
Wow, cool! I have few questions:

1. Is it really safe to remove proc_info? 
2. How did you come up with the solution in rtsx_scsi.c shown [here](https://github.com/Zibri/Realtek-rts5229-linux-driver/commit/9c94e33c7f5586d626069b4b35484119d59439fb#diff-70364edd9b090fb20b9b4b9ba8866b34)?
3. Can I merge your changes in my patch? Or, best, do you want to make a pull request so that you also get the credits you deserve ;) ?

**Comment by Zibri** [comment] 2017-12-01 17:37
Well.. I searched for "static int inquiry(struct scsi_cmnd" on google and found the same routine in a different driver, so I tried that and it worked.
Ok.. how do I make a pull request? I never did until now.
About (1) I don't know but the driver works perfectly.

**Comment by Zibri** [comment] 2017-12-01 17:47
About the pull request I didn't fork your github, I applied the patch and created a new repository so it's easier to just clone, compile and install..
I can include your patch in some header if you want... but I think most of the good code is in the 5139 sources...

**Comment by Zibri** [comment] 2017-12-01 17:48
Oh and I removed proc_info because it was not referenced in my code and I had the unused warning.

**Comment by M0Rf30** [comment] 2017-12-21 16:18
this https://github.com/astyonax/patched-RTS5227-5229/pull/3 fix the current issue with latest kernel

**Comment by astyonax** [comment] 2018-01-09 08:21
I merged the pull request, thus I close also this issue.
Thank you all for the collaboration.

**Closed as completed by astyonax** 2018-01-09 08:21 UTC
